version: 5.214.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU
init:
- ps: ''
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  SolutionDir: C:\projects\chummer\
  CHUMMER_OAUTH_TOKEN: 831e3c01126ca8da4661fe3d48a15c1c0bb2c5cb
  matrix:
  - project_name: Chummer
    api_token: 'secure: Ez1QcWiKJJWMAO+xXkQglJNI4OnWM5/JMjXgy6gwJH5IuUX4ttzrpthVYNjHWS12'
install:
- ps: ''
nuget:
  disable_publish_on_pr: true
cache:
  - packages -> **\packages.config
before_build:
- ps: |
    $token = $env:api_token
    $headers = @{
        "Authorization" = "Bearer $token"
        "Content-type" = "application/json"
    }
    $apiURL = "https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG"
    $history = Invoke-RestMethod -Uri "$apiURL/history?recordsNumber=2" -Headers $headers  -Method Get
    $exitBuild = $false
    if ($history.builds.Count -eq 2)
    {
        $CurrentCommitID = $history.builds[0].commitId
        $PreviousCommitID = $history.builds[1].commitId
        Write-host "Current Commit ID: $CurrentCommitID"
        Write-host "Previous Commit ID: $PreviousCommitID"
        if (($CurrentCommitID -eq $PreviousCommitID) -and ($env:APPVEYOR_SCHEDULED_BUILD -eq $true))
        {
            Write-host "Current Commit ID is the same as previous, exiting build."
            $exitBuild = $true
        }
    }
    # Needs to be in this format, otherwise Exit-AppVeyorBuild won't work. That command has to be the final one executed in the script
    if ($exitBuild)
    {
        Exit-AppVeyorBuild
    }
    else
    {
        nuget restore
        & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\TextTransform.exe' 'C:\projects\chummer\Chummer\Properties\contributors.tt'
        Set-AppveyorBuildVariable -Name OldMinorVersion -Value $($env:APPVEYOR_BUILD_VERSION).Split('.')[1]
        Write-Host "Environment Variable: $env:OldMinorVersion"
        $Assemblyfile = "C:\projects\chummer\Chummer\Properties\AssemblyInfo.cs"
        $regex = new-object System.Text.RegularExpressions.Regex ('(AssemblyVersion(Attribute)?\s*\(\s*\")(.*)(\"\s*\))',  [System.Text.RegularExpressions.RegexOptions]::MultiLine)
        $content = [IO.File]::ReadAllText($assemblyFile)
        $version = $null
        $match = $regex.Match($content)
        if($match.Success) {
        $version = $match.groups[3].value
        }
        $Major = $version.Split('.')[0]
        $Minor = $version.Split('.')[1]
        if ($Minor -ne $($env:OldMinorVersion))
        {
          Write-Host "Current Minor: $Minor"
          Write-Host "Old Minor: $($env:OldMinorVersion))"
          Write-Host "Resetting build version to 1, assuming that a new .0 release has been issued already."
          $apiUrl = 'https://ci.appveyor.com/api/projects/$accountName/$projectSlug'
          $BuildNumber = '{ nextBuildNumber: 1; }'
          $Format = '{ versionFormat: $Major.$Minor.1; }'
          # get project with last build details
          Invoke-RestMethod -Method Put -Uri "$apiUrlsettings/build-number" -Headers $headers -Body $BuildNumber
          Invoke-RestMethod -Method Put -Uri "$apiUrl/settings" -Headers $headers -Body $BuildNumber
          Update-AppveyorBuild -Version "$Major.$Minor.1"
        }
        else
        {
          Update-AppveyorBuild -Version "$Major.$Minor.$env:appveyor_build_number"
        }
    }
build:
  project: Chummer.sln
  verbosity: normal
after_build:
- ps: 7z a Chummer.Nightly.zip C:\projects\chummer\Chummer\bin\release\* -r
test_script:
- cmd: vstest.console /logger:Appveyor "%APPVEYOR_BUILD_FOLDER%\Chummer.Tests\bin\Release\Chummer.Tests.dll"
artifacts:
- path: Chummer.Nightly.zip
  name: Chummer
deploy:
- provider: GitHub
  tag: Nightly-v$(appveyor_build_version)
  auth_token:
    secure: xrNlPolUlOE6KAfl/ZDdT8kdVxlzMZXfvafmN92gRYHGh6b2XcwXNi8K1+f0LO6m
  artifact: Chummer
  draft: false
  prerelease: true
on_failure:
- ps: |
    Update-AppveyorBuild -Version "$Major.$Minor.$env:appveyor_build_number-$(Get-Date -format HHmmss)-failed"
    if ($env:APPVEYOR_SCHEDULED_BUILD -eq $true)
    {
      Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
      ./send.ps1 failure https://discord.com/api/webhooks/776194471510671361/IZvRFV0SdIlwNO4b2PzSfvMmRtkc-bZeiDqoimm_CbaVwOCsyQmAOhH5WfL0fSgLZqRu
    }
